# API Contract: Update Task
# PUT/PATCH /api/v1/users/{user_id}/tasks/{task_id}

openapi: 3.0.3
info:
  title: Update Task API
  version: 1.0.0

paths:
  /api/v1/users/{user_id}/tasks/{task_id}:
    put:
      operationId: updateTaskFull
      summary: Full update of a task
      description: Updates all fields of a task (title, description, completed)
      tags:
        - Tasks
      security:
        - BearerAuth: []
      parameters:
        - name: user_id
          in: path
          required: true
          description: User ID (must match JWT sub claim)
          schema:
            type: string
            example: "550e8400-e29b-41d4-a716-446655440000"
        - name: task_id
          in: path
          required: true
          description: Task UUID
          schema:
            type: string
            format: uuid
            example: "f47ac10b-58cc-4372-a567-0e02b2c3d479"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdateFull'
            example:
              title: "Buy groceries (updated)"
              description: "Milk, eggs, bread, vegetables, and cheese"
              completed: true
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
              example:
                id: "f47ac10b-58cc-4372-a567-0e02b2c3d479"
                user_id: "550e8400-e29b-41d4-a716-446655440000"
                title: "Buy groceries (updated)"
                description: "Milk, eggs, bread, vegetables, and cheese"
                completed: true
                created_at: "2026-01-10T10:30:00Z"
                updated_at: "2026-01-10T14:45:00Z"
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '401':
          description: Unauthorized - Missing or invalid JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Task not found or does not belong to user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                detail: "Task not found"
                code: "NOT_FOUND"
        '429':
          description: Rate limit exceeded
          headers:
            Retry-After:
              schema:
                type: integer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    patch:
      operationId: updateTaskPartial
      summary: Partial update of a task
      description: Updates only the provided fields of a task
      tags:
        - Tasks
      security:
        - BearerAuth: []
      parameters:
        - name: user_id
          in: path
          required: true
          description: User ID (must match JWT sub claim)
          schema:
            type: string
            example: "550e8400-e29b-41d4-a716-446655440000"
        - name: task_id
          in: path
          required: true
          description: Task UUID
          schema:
            type: string
            format: uuid
            example: "f47ac10b-58cc-4372-a567-0e02b2c3d479"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdatePartial'
            examples:
              mark_complete:
                summary: Mark task as complete
                value:
                  completed: true
              update_title:
                summary: Update title only
                value:
                  title: "Buy groceries tomorrow"
              update_multiple:
                summary: Update multiple fields
                value:
                  title: "Buy groceries tomorrow"
                  description: "Updated shopping list"
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
              example:
                id: "f47ac10b-58cc-4372-a567-0e02b2c3d479"
                user_id: "550e8400-e29b-41d4-a716-446655440000"
                title: "Buy groceries"
                description: "Milk, eggs, bread"
                completed: true
                created_at: "2026-01-10T10:30:00Z"
                updated_at: "2026-01-10T14:45:00Z"
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '401':
          description: Unauthorized - Missing or invalid JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Task not found or does not belong to user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                detail: "Task not found"
                code: "NOT_FOUND"
        '429':
          description: Rate limit exceeded
          headers:
            Retry-After:
              schema:
                type: integer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    TaskUpdateFull:
      type: object
      required:
        - title
        - completed
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 255
          description: Task title (required)
        description:
          type: string
          maxLength: 2000
          nullable: true
          description: Task description
        completed:
          type: boolean
          description: Task completion status (required)

    TaskUpdatePartial:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 255
          description: Task title (optional)
        description:
          type: string
          maxLength: 2000
          nullable: true
          description: Task description (optional)
        completed:
          type: boolean
          description: Task completion status (optional)
      minProperties: 1

    TaskResponse:
      type: object
      required:
        - id
        - user_id
        - title
        - completed
        - created_at
        - updated_at
      properties:
        id:
          type: string
          format: uuid
          description: Unique task identifier
        user_id:
          type: string
          description: Owner's user ID
        title:
          type: string
          description: Task title
        description:
          type: string
          nullable: true
          description: Task description
        completed:
          type: boolean
          description: Task completion status
        created_at:
          type: string
          format: date-time
          description: Creation timestamp (ISO 8601)
        updated_at:
          type: string
          format: date-time
          description: Last update timestamp (ISO 8601)

    ValidationError:
      type: object
      properties:
        detail:
          type: string
        code:
          type: string
        errors:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
              message:
                type: string

    ErrorResponse:
      type: object
      properties:
        detail:
          type: string
          description: Human-readable error message
        code:
          type: string
          description: Machine-readable error code
