apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-ai-chatbot.backend.fullname" . }}
  labels:
    {{- include "todo-ai-chatbot.backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      {{- if and (eq .Values.backend.service.type "NodePort") .Values.backend.service.nodePort }}
      nodePort: {{ .Values.backend.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
    {{- include "todo-ai-chatbot.backend.selectorLabels" . | nindent 4 }}
